site_name: Jonathan Monette | Personal Site
site_author: jmoney
site_description: ""
site_keyword: "jmoney, jonathan monette, engineer"
site_favicon: favicon.ico
docs_dir: docs

plugins:
  - search
  - macros
  - include-markdown

nav:
  - Home: https://www.jmoney.dev/
  - Blogs: https://www.jmoney.dev/blogs/
  - Cloud: https://www.jmoney.dev/cloud/
  - Homebrew: https://www.jmoney.dev/homebrew/
  - TIL: 'https://www.jmoney.dev/til/'
  - Resume: 'https://github.com/jmoney/resume/releases/download/latest/JonathanMonette_resume.pdf'

theme:
  name: github
  highlightjs: true
  hljs_style: github