site_name: Jonathan Monette | Personal Site
site_author: jmoney
site_description: ""
site_keyword: "jmoney, jonathan monette, engineer"
docs_dir: docs

plugins:
  - search
  - macros
  - include-markdown

nav:
  - Home: https://www.jmoney.dev/
  - Blogs: https://www.jmoney.dev/blogs/
  - Cloud: https://www.jmoney.dev/cloud/
  - Homebrew: https://www.jmoney.dev/homebrew/
  - TIL: 'https://www.jmoney.dev/til/'
  - Resume: 'https://github.com/jmoney/resume/releases/download/latest/JonathanMonette_resume.pdf'

# TODO - Fix table of contents.  When using the include-markdown plugin, the TOC is not generated.
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.follow
  icon:
    repo: fontawesome/brands/github
hooks:
  - hooks/config/inject_git_repo.py

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmoney/
      name: Jmoney on Github

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jmoney9001/
      name: Jmoney on LinkedIn