site_name: Jonathan Monette | Personal Site
site_author: jmoney
site_description: ""
site_keyword: "jmoney, jonathan monette, engineer"
docs_dir: docs

plugins:
  - search
  - macros
  - include-markdown

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: black
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.follow
  icon:
    repo: fontawesome/brands/github
hooks:
  - hooks/config/inject_git_repo.py
  - hooks/template_context/inject_tabs.py

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmoney/
      name: Jmoney on Github

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jmoney9001/
      name: Jmoney on LinkedIn